site_name: Retail Demo Store
repo_url: https://github.com/aws-samples/retail-demo-store
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  logo: assets/logo.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

